### PR TITLE
Drawstyle

### PR DESCRIPTION
**Pull request by genomematt**
mplexporter component of fix to mpld3 issue #207

### CODE REVIEW

**Comment by aflaxman** [comment]
Looks like something has gone wrong with our TravisCI setup (something different than in https://github.com/jakevdp/mpld3/pull/350):

```
$ ./miniconda.sh -b
PREFIX=/home/travis/miniconda2
installing: _cache-0.0-py27_x0 ...
installing: python-2.7.11-0 ...
installing: conda-env-2.4.5-py27_0 ...
installing: openssl-1.0.2d-0 ...
installing: pycosat-0.6.1-py27_0 ...
installing: pyyaml-3.11-py27_1 ...
installing: readline-6.2-2 ...
installing: requests-2.9.0-py27_0 ...
installing: sqlite-3.8.4.1-1 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-0 ...
installing: conda-3.19.0-py27_0 ...
installing: pycrypto-2.6.1-py27_0 ...
installing: pip-7.1.2-py27_0 ...
installing: wheel-0.26.0-py27_1 ...
installing: setuptools-18.8.1-py27_0 ...
Python 2.7.11 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
before_install.6
0.00s$ export PATH="$HOME/miniconda/bin:$PATH"
0.00s$ conda update --yes conda
/home/travis/build.sh: line 45: conda: command not found
The command "conda update --yes conda" failed and exited with 127 during .
```

@jakevdp @danielballan have time to debug this?

**Comment by genomematt** [comment]
@aflaxman can we try this again post #46 ?  The other patch can be revised if this goes in

**Comment by aflaxman** [comment]
I think I know how to do that...  let's see if this works: https://travis-ci.org/mpld3/mplexporter/builds/117623326

**Comment by aflaxman** [comment]
@genomematt can you try merging #46 (or current master) into your PR?

**Comment by genomematt** [comment]
@aflaxman master merged and checks now pass

**Comment by aflaxman** [comment]
Thanks for your patience with this!

**Pull request merged**
